config/routes.rb
Rails.application.routes.draw do
  
  root to: "lists#index"
  
  
  resources :lists 
  resources :cards
  resources :webhooks, defaults: {format: 'json'}
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list

  def self.post_card(card)
    url = "https://api.trello.com/1/cards?idList=#{ENV["TDO_ID"]}&key=#{ENV["TRL_KEY"]}&token=#{ENV["TRL_TOKEN"]}"
    payload = card.to_json
    header = { content_type: :json, accept: :json }

    RestClient.post(url, payload, header) 
  end
end


  

  

app/models/list.rb
class List < ApplicationRecord
    has_many :cards, dependent: :destroy

    def self.get_list 
        url =  "https://api.trello.com/1/boards/#{ENV["BOARD_ID"]}/lists?cards=all&fields=name&key=#{ENV["TRL_KEY"]}&token=#{ENV["TRL_TOKEN"]}"

        response = RestClient.get(url)
        list_data = JSON.parse(response)
    end 
end

app/models/webhook.rb
class Webhook < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end
 

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def index;end

    def new
        @card = Card.new
    end

    # Create a card to Trello
    def create 
        card = Card.new(post_params)
        if Card.post_card(card)
        redirect_to lists_path, notice: "New card successfully created!"
        else
            render :new
        end
    end

    private

    def post_params
          params.require(:card).permit(:name)
    end  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @listing = List.get_list
    end
    
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    protect_from_forgery with: :null_session
    require 'json'

    def index
        render json:{}, status: 200
    end

    def create
        puts "Incoming webhook:"
        begin
            if params["webhook"]["action"]["display"]["entities"].present?
                puts "Card '" + 
                    params["webhook"]["action"]["display"]["entities"]["card"]["text"].to_s + "' moved to '" + 
                    params["webhook"]["action"]["display"]["entities"]["listAfter"]["text"].to_s + "'"
            end
        rescue => exception
            puts "Could not process webhook"
        end

        render json:{}, status: 200
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
    
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/cards/_form.html.erb
<div>
    <%= form_with(model: card, local: true)  do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>

        <%= f.submit class:"create-btn" %>
    <% end %>
</div>

app/views/cards/new.html.erb
<p>Please add a card...</p>

<%= render "form", card: @card %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; 2018-<%= Time.now.year %>
      <%= link_to 'Offerzen','https://offerzen.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="image">
    <%= link_to image_tag("placeholder"), root_path %>
    <ul>
      <p>
        The Pizza Project
      </p>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pizza Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/lists/index.html.erb
<h2>The Project lists</h2>

<table>
    <tr>
        <% @listing.each do |list| %>
              <th><%= list["name"] %></th>
                <% list["cards"].each do |card| %> 
                    <% if !card["closed"] %> 
                    <tr><td><%= card["name"] %></td></tr> 
                    <% end %>
            <% end %>
        <% end %>
    </tr>
</table>


<div class="access">
    <section class="">
    <%= link_to "+Add Card", new_card_path, class: "link-btn" %>
    </section>
</div>